######################################################### {COPYRIGHT-TOP} ###
# Licensed Materials - Property of IBM
# 5900-AEO
#
# Copyright IBM Corp. 2020, 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication, or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
######################################################### {COPYRIGHT-END} ###
# Small Ephemeral Profile
# The license value is set to false, while using this CR, set it to true
apiVersion: base.automation.ibm.com/v1beta1
kind: AutomationBase
metadata:
  name: small-ephemeral
spec:
  license:
    accept: false
  tls: {}
  version: 1.0.0
  kafka:
    kafka:
      config:
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 1000m
          memory: 1Gi
      storage:
        type: ephemeral
    zookeeper:
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 1000m
          memory: 1Gi
      storage:
        type: ephemeral
  elasticsearch:
    nodegroupspecs:
      - name: master-data
        replicas: 1
        template:
          pod:
            spec:
              containers:
                - name: elasticsearch
                  resources:
                    requests:
                      cpu: 1000m
                      memory: 2Gi
                    limits:
                      cpu: 1000m
                      memory: 2Gi
